name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Updated to v3 for latest features

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3 to support Node.js 20
        with:
          node-version: '20'  # Set to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build
        env:
          REACT_APP_USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          REACT_APP_CLIENT_ID: ${{ secrets.CLIENT_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # or wherever your build output is
