name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Checkout code

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Set up Node.js to run build scripts
        with:
          node-version: '20'  # Use Node.js 20

      - name: Inject environment variables into static files
        run: node build.js
        env:
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # This is where the generated site is
